### ISSUE TITLE
Uncaught DOMException: Failed to execute 'setEnd' on 'Range'

### ISSUE THREAD

**Issue by jmatsushita** [benweet/stackedit#1053]
On a self hosted version of StackEdit 4.3.14 after moving text around that had comments attached to it, when trying to open one of the comments I can't open one of the comments and I get repeated (more than thousands) messages in the console:
```
Uncaught DOMException: Failed to execute 'setEnd' on 'Range': The offset -1622 is larger than or equal to the node's length (3).
    at d.createRange (https://stack.../res-min/main.js:23581:60)
    at HTMLDivElement.<anonymous> (https://stack.../res-min/main.js:21318:25)
    at HTMLDivElement.dispatch (https://stack.../res-min/main.js:1604:85)
    at HTMLDivElement.v.handle (https://stack.../res-min/main.js:1545:91)
    at Object.trigger (https://stack.../res-min/main.js:1591:76)
    at HTMLAnchorElement.<anonymous> (https://stack.../res-min/main.js:1774:14)
    at Function.each (https://stack.../res-min/main.js:474:40)
    at init.each (https://stack.../res-min/main.js:358:14)
    at init.trigger (https://stack.../res-min/main.js:1773:16)
    at t.show (https://stack.../res-min/main.js:20453:22)
```

**Comment by benweet** [comment]
Closing this. Comments will be available soon in the v5 (https://stackedit.io/app).
