### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by shockerli** [benweet/stackedit#1253]
When I perform the installation, report the following error. Please help me, thanks~
```
npm install stackedit
npm ERR! Unexpected end of JSON input while parsing near '..."^1.0.4","markdown-it'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shocker/.npm/_logs/2018-03-05T07_18_51_989Z-debug.log
```

**Log content:**
`/Users/shocker/.npm/_logs/2018-03-05T07_18_51_989Z-debug.log`
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'stackedit' ]
2 info using npm@5.5.1
3 info using node@v8.9.2
4 verbose npm-session 001a4d66ed658156
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npm.taobao.org/stackedit 516ms
8 silly pacote tag manifest for stackedit@latest fetched in 570ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule stackedit@5.8.0 checking installable status
14 http fetch GET 200 https://registry.npm.taobao.org/clipboard 115ms
15 silly pacote range manifest for clipboard@^1.7.1 fetched in 123ms
16 silly resolveWithNewModule clipboard@1.7.1 checking installable status
17 http fetch GET 200 https://registry.npm.taobao.org/compression 199ms
18 http fetch GET 304 https://registry.npm.taobao.org/bezier-easing 204ms (from cache)
19 http fetch GET 304 https://registry.npm.taobao.org/handlebars 244ms (from cache)
20 http fetch GET 304 https://registry.npm.taobao.org/body-parser 251ms (from cache)
21 http fetch GET 304 https://registry.npm.taobao.org/file-saver 259ms (from cache)
22 http fetch GET 304 https://registry.npm.taobao.org/diff-match-patch 260ms (from cache)
23 silly pacote range manifest for body-parser@^1.18.2 fetched in 265ms
24 silly resolveWithNewModule body-parser@1.18.2 checking installable status
25 silly pacote range manifest for compression@^1.7.0 fetched in 270ms
26 silly resolveWithNewModule compression@1.7.2 checking installable status
27 http fetch GET 304 https://registry.npm.taobao.org/google-id-token-verifier 271ms (from cache)
28 silly pacote range manifest for bezier-easing@^1.1.0 fetched in 276ms
29 silly resolveWithNewModule bezier-easing@1.1.1 checking installable status
30 http fetch GET 304 https://registry.npm.taobao.org/js-yaml 159ms (from cache)
31 http fetch GET 304 https://registry.npm.taobao.org/indexeddbshim 279ms (from cache)
32 silly pacote range manifest for js-yaml@^3.9.1 fetched in 170ms
33 silly resolveWithNewModule js-yaml@3.10.0 checking installable status
34 silly pacote range manifest for handlebars@^4.0.10 fetched in 293ms
35 silly resolveWithNewModule handlebars@4.0.11 checking installable status
36 silly pacote range manifest for diff-match-patch@^1.0.0 fetched in 303ms
37 silly resolveWithNewModule diff-match-patch@1.0.0 checking installable status
38 silly pacote range manifest for file-saver@^1.3.3 fetched in 305ms
39 silly resolveWithNewModule file-saver@1.3.3 checking installable status
40 silly pacote range manifest for google-id-token-verifier@^0.2.3 fetched in 312ms
41 silly resolveWithNewModule google-id-token-verifier@0.2.3 checking installable status
42 http fetch GET 304 https://registry.npm.taobao.org/aws-sdk 330ms (from cache)
43 silly pacote range manifest for indexeddbshim@^3.0.4 fetched in 337ms
44 silly resolveWithNewModule indexeddbshim@3.5.0 checking installable status
45 silly pacote trying http://registry.npm.taobao.org/indexeddbshim/download/indexeddbshim-3.5.0.tgz by hash: sha1-2twww9xh7Bjx3NVjpCSqu6hDKpI=
46 silly pacote data for sha1-2twww9xh7Bjx3NVjpCSqu6hDKpI= not present. Using manifest.
47 silly pacote range manifest for aws-sdk@^2.133.0 fetched in 377ms
48 silly resolveWithNewModule aws-sdk@2.205.0 checking installable status
49 http fetch GET 304 https://registry.npm.taobao.org/katex 122ms (from cache)
50 http fetch GET 304 https://registry.npm.taobao.org/markdown-it 122ms (from cache)
51 silly fetchPackageMetaData error for markdown-it@^8.3.1 Unexpected end of JSON input while parsing near '..."^1.0.4","markdown-it'
52 http fetch GET 304 https://registry.npm.taobao.org/markdown-it-abbr 128ms (from cache)
53 http fetch GET 304 https://registry.npm.taobao.org/markdown-it-deflist 123ms (from cache)
54 silly pacote range manifest for katex@^0.9.0-alpha1 fetched in 165ms
55 silly resolveWithNewModule katex@0.9.0 checking installable status
56 http fetch GET 304 https://registry.npm.taobao.org/markdown-it-emoji 139ms (from cache)
57 silly pacote range manifest for markdown-it-abbr@^1.0.4 fetched in 166ms
58 silly resolveWithNewModule markdown-it-abbr@1.0.4 checking installable status
59 http fetch GET 304 https://registry.npm.taobao.org/markdown-it-footnote 146ms (from cache)
60 http fetch GET 304 https://registry.npm.taobao.org/markdown-it-pandoc-renderer 141ms (from cache)
61 silly pacote range manifest for markdown-it-deflist@^2.0.2 fetched in 167ms
62 silly resolveWithNewModule markdown-it-deflist@2.0.3 checking installable status
63 http fetch GET 304 https://registry.npm.taobao.org/markdown-it-sub 149ms (from cache)
64 silly pacote range manifest for markdown-it-emoji@^1.3.0 fetched in 181ms
65 silly resolveWithNewModule markdown-it-emoji@1.4.0 checking installable status
66 http fetch GET 304 https://registry.npm.taobao.org/markdown-it-sup 137ms (from cache)
67 silly pacote range manifest for markdown-it-footnote@^3.0.1 fetched in 187ms
68 silly resolveWithNewModule markdown-it-footnote@3.0.1 checking installable status
69 silly pacote version manifest for markdown-it-pandoc-renderer@1.1.3 fetched in 184ms
70 silly resolveWithNewModule markdown-it-pandoc-renderer@1.1.3 checking installable status
71 silly pacote range manifest for markdown-it-sub@^1.0.0 fetched in 189ms
72 silly resolveWithNewModule markdown-it-sub@1.0.0 checking installable status
73 silly pacote range manifest for markdown-it-sup@^1.0.0 fetched in 173ms
74 silly resolveWithNewModule markdown-it-sup@1.0.0 checking installable status
75 http fetch GET 304 https://registry.npm.taobao.org/mousetrap 130ms (from cache)
76 http fetch GET 304 https://registry.npm.taobao.org/mermaid 163ms (from cache)
77 silly pacote range manifest for mousetrap@^1.6.1 fetched in 153ms
78 silly resolveWithNewModule mousetrap@1.6.1 checking installable status
79 http fetch GET 304 https://registry.npm.taobao.org/prismjs 105ms (from cache)
80 http fetch GET 304 https://registry.npm.taobao.org/normalize-scss 115ms (from cache)
81 silly pacote range manifest for mermaid@^7.1.0 fetched in 177ms
82 silly resolveWithNewModule mermaid@7.1.2 checking installable status
83 silly pacote range manifest for prismjs@^1.6.0 fetched in 118ms
84 silly resolveWithNewModule prismjs@1.11.0 checking installable status
85 silly pacote range manifest for normalize-scss@^7.0.0 fetched in 130ms
86 silly resolveWithNewModule normalize-scss@7.0.1 checking installable status
87 http fetch GET 304 https://registry.npm.taobao.org/request 112ms (from cache)
88 silly pacote range manifest for request@^2.82.0 fetched in 116ms
89 silly resolveWithNewModule request@2.83.0 checking installable status
90 http fetch GET 304 https://registry.npm.taobao.org/turndown 84ms (from cache)
91 http fetch GET 304 https://registry.npm.taobao.org/tmp 86ms (from cache)
92 silly pacote range manifest for tmp@^0.0.33 fetched in 88ms
93 silly resolveWithNewModule tmp@0.0.33 checking installable status
94 silly pacote range manifest for turndown@^4.0.1 fetched in 92ms
95 silly resolveWithNewModule turndown@4.0.1 checking installable status
96 http fetch GET 304 https://registry.npm.taobao.org/vuex 74ms (from cache)
97 silly pacote range manifest for vuex@^2.3.1 fetched in 81ms
98 silly resolveWithNewModule vuex@2.5.0 checking installable status
99 http fetch GET 304 https://registry.npm.taobao.org/vue 99ms (from cache)
100 silly pacote range manifest for vue@^2.3.3 fetched in 108ms
101 silly resolveWithNewModule vue@2.5.13 checking installable status
102 http fetch GET 200 https://registry.npm.taobao.org/serve-static 152ms
103 silly pacote range manifest for serve-static@^1.12.6 fetched in 157ms
104 silly resolveWithNewModule serve-static@1.13.2 checking installable status
105 http fetch GET 200 https://registry.npm.taobao.org/indexeddbshim/download/indexeddbshim-3.5.0.tgz 1830ms
106 silly pacote http://registry.npm.taobao.org/indexeddbshim/download/indexeddbshim-3.5.0.tgz extracted in 1847ms
107 silly addBundled read tarball
108 silly cleanup remove extracted module
109 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."^1.0.4","markdown-it'
109 verbose stack     at JSON.parse (<anonymous>)
109 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
109 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
109 verbose stack     at <anonymous>
109 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
110 verbose cwd /Users/shocker/code/stackedit
111 verbose Darwin 17.4.0
112 verbose argv "/usr/local/Cellar/node/8.9.2/bin/node" "/usr/local/bin/npm" "install" "stackedit"
113 verbose node v8.9.2
114 verbose npm  v5.5.1
115 error Unexpected end of JSON input while parsing near '..."^1.0.4","markdown-it'
116 verbose exit [ 1, true ]

```

**Comment by shockerli** [comment]
```
npm cache clear --force
npm install
```
