### ISSUE TITLE
I don't know where the mistake is. Is it installed problem or code or depends on the package?

### ISSUE THREAD

**Issue by kwooshung** [benweet/stackedit#1307]
# Base Config
system:mac os last version
node:v10.0.0
npm:6.0.0

# Then I got stuck here, so I used Taobao's NPM mirror source.
```
myMBP:stackedit JohnWick$ sudo npm install
Password:
Unhandled rejection Error: Command failed: /usr/bin/git clone --depth=1 -q -b configurable https://github.com/brettz9/node-websql.git /Users/JohnWick/.npm/_cacache/tmp/git-clone-5527f5eb
/Users/JohnWick/.npm/_cacache/tmp/git-clone-5527f5eb/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:282:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:947:16)
    at Socket.stream.socket.on (internal/child_process.js:368:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:598:12)

Unhandled rejection Error: Command failed: /usr/bin/git clone --depth=1 -q -b full-sync-missing-promise-features https://github.com/brettz9/sync-promise.git /Users/JohnWick/.npm/_cacache/tmp/git-clone-6e71e96c
/Users/JohnWick/.npm/_cacache/tmp/git-clone-6e71e96c/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:282:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:947:16)
    at Socket.stream.socket.on (internal/child_process.js:368:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:598:12)

⸨            ░░░░░░⸩ ⠧ extract:sqlite3: sill extract babel-plugin-syntax-async-functions@6.13.0
```

# Taobao's NPM mirror source.
npm I used a mirror image of Taobao
https://npm.taobao.org/

```
myMBP:2017 JohnWick$ cd stackedit
myMBP:stackedit JohnWick$ sudo cnpm install
⠋ [20/87] Installing match-at@^0.1.1[indexeddbshim@3.6.1 › sync-promise@git+https://github.com/brettz9/sync-promise.git#full-sync-missing-promise-features] install sync-promise from git git+https://github.com/brettz9/sync-promise.git#full-sync-missing-promise-features, may be very slow, please keep patience
[indexeddbshim@3.6.1 › websql@git+https://github.com/brettz9/node-websql.git#configurable] install websql from git git+https://github.com/brettz9/node-websql.git#configurable, may be very slow, please keep patience
✔ Installed 87 packages
✔ Linked 1010 latest versions
node-pre-gyp http GET https://npm.taobao.org/mirrors/fsevents/v1.2.3/fse-v1.2.3-node-v64-darwin-x64.tar.gz
node-pre-gyp http 302 https://npm.taobao.org/mirrors/fsevents/v1.2.3/fse-v1.2.3-node-v64-darwin-x64.tar.gz
node-pre-gyp http 200 https://npm.taobao.org/mirrors/fsevents/v1.2.3/fse-v1.2.3-node-v64-darwin-x64.tar.gz
[fsevents] Success: "/Users/JohnWick/project/website/2017/stackedit/node_modules/_fsevents@1.2.3@fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/JohnWick/project/website/2017/stackedit/node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1525243092720/phantomjs-2.1.1-macosx -> /Users/JohnWick/project/website/2017/stackedit/node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/JohnWick/project/website/2017/stackedit/node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt/lib/phantom/bin/phantomjs
Cached binary found at /Users/JohnWick/.npminstall_tarball/node-sass/4.9.0/darwin-x64-64_binding.node
Binary found at /Users/JohnWick/project/website/2017/stackedit/node_modules/_node-sass@4.9.0@node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
node-pre-gyp http GET https://npm.taobao.org/mirrors/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://npm.taobao.org/mirrors/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://npm.taobao.org/mirrors/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.0.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://npm.taobao.org/mirrors/sqlite3/v3.1.13/node-v64-darwin-x64.tar.gz 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
In file included from ../../_nan@2.7.0@nan/nan.h:192:
../../_nan@2.7.0@nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../_nan@2.7.0@nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/JohnWick/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/JohnWick/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../_nan@2.7.0@nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/JohnWick/.node-gyp/10.0.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/JohnWick/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../_nan@2.7.0@nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/JohnWick/.node-gyp/10.0.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/JohnWick/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../_nan@2.7.0@nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/JohnWick/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/JohnWick/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../src/database.cc:144:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:525:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:625:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
8 warnings and 1 error generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/JohnWick/project/website/2017/stackedit/node_modules/_node-gyp@3.6.2@node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/JohnWick/project/website/2017/stackedit/node_modules/_node-gyp@3.6.2@node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3/lib/binding/node-v64-darwin-x64"
gyp ERR! cwd /Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/JohnWick/project/website/2017/stackedit/node_modules/_node-gyp@3.6.2@node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3/lib/binding/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /Users/JohnWick/project/website/2017/stackedit/node_modules/_node-gyp@3.6.2@node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/JohnWick/project/website/2017/stackedit/node_modules/_sqlite3@3.1.13@sqlite3/lib/binding/node-v64-darwin-x64' (1)
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node-pre-gyp install --fallback-to-build" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node-pre-gyp install --fallback-to-build" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:947:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
npminstall version: 3.5.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/JohnWick/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org
```

# Preview Mermaid
![image](https://user-images.githubusercontent.com/3413930/39510216-848e9f9a-4e1b-11e8-9fbe-0971837247a4.png)

**Comment by benweet** [comment]
You have some "Permission denied" errors, I suppose it's because of your environment.

**Comment by kwooshung** [comment]
but i use `sudo`, why?
