### ISSUE TITLE
Change Port from 8080

### ISSUE THREAD

**Issue by bionichuman** [benweet/stackedit#1369]
Is it possible to change the port it runs on from 8080 to something else?

**Comment by flxwu** [comment]
Yes, you can by altering the port number on line 26 in `./config/index.js`.

**Comment by bionichuman** [comment]
@flxwu it worked. Thank You. Now I keep getting error code 3..


Compiled successfully in 67036ms                              11:07:15 PM

> Listening at http://localhost:8081

(node:25540) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/home/stackedit/node_modules/opn/index.js:83:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:25540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
