### ISSUE TITLE
Google Drive sync timeouts

### ISSUE THREAD

**Issue by fuxoft** [benweet/stackedit#263]
I am often getting timeout when trying to sync with Google Drive. The three rectangles at the top keep animating for a while and then I get this in the Console:

Uncaught TypeError: Object [object Object] has no method 'execute' main.js:29817
Error: A timeout occurred.
    at r (https://stackedit.io/res-min/main.js:29250:65)
    at https://stackedit.io/res-min/main.js:23183:8
    at Array.forEach (native)
    at Function.E.each.E.forEach (https://stackedit.io/res-min/main.js:3625:46)
    at Object.onPeriodicRun (https://stackedit.io/res-min/main.js:23181:6)
    at https://stackedit.io/res-min/main.js:29017:79 main.js:23185
(anonymous function)

Tried resetting the StackEdit, it helped only for a while

**Comment by benweet** [comment]
Closing as too old.
