### ISSUE TITLE
New installation has several errors during build

### ISSUE THREAD

**Issue by bdeanindy** [benweet/stackedit#958]
Thought I would share the error list on a brand new installation.

```
~/GIT_CLONES/stackedit (HEAD: ref: refs/heads/master) $ gulp
[05:13:14] Using gulpfile ~/GIT_CLONES/stackedit/Gulpfile.js
[05:13:14] Starting 'default'...
[05:13:14] Starting 'jshint'...
[05:13:14] Starting 'clean-requirejs'...
[05:13:14] Starting 'constants'...
[05:13:14] Starting 'clean-less'...
[05:13:14] Starting 'clean-font'...
[05:13:14] Starting 'clean-img'...
[05:13:14] Finished 'clean-less' after 133 ms
[05:13:14] Starting 'less'...
[05:13:14] Finished 'clean-font' after 136 ms
[05:13:14] Starting 'copy-font'...
[05:13:14] Finished 'clean-img' after 137 ms
[05:13:14] Starting 'copy-img'...
[05:13:14] Finished 'clean-requirejs' after 173 ms
[05:13:14] Starting 'copy-requirejs'...
[05:13:14] Finished 'constants' after 171 ms
[05:13:15] Finished 'copy-requirejs' after 475 ms
[05:13:15] Starting 'requirejs'...
public/res/classes/AsyncTask.js: line 135, col 14, 'runTask' was used before it was defined.
public/res/classes/AsyncTask.js: line 171, col 14, 'runSafe' was used before it was defined.

2 errors
public/res/extensions/comments.js: line 251, col 14, 'getDiscussionComments' was used before it was defined.

1 error
public/res/extensions/documentManager.js: line 99, col 14, 'doDelete' was used before it was defined.

1 error
public/res/extensions/documentPanel.js: line 175, col 13, '$filterInputElt' was used before it was defined.

1 error
public/res/extensions/findReplace.js: line 53, col 14, 'resetSelect' was used before it was defined.

1 error
public/res/extensions/htmlSanitizer.js: line 37, col 14, 'sanitizeUri' was used before it was defined.
public/res/extensions/htmlSanitizer.js: line 135, col 14, 'htmlParser' was used before it was defined.
public/res/extensions/htmlSanitizer.js: line 175, col 18, 'parseEndTag' was used before it was defined.
public/res/extensions/htmlSanitizer.js: line 297, col 14, 'decodeEntities' was used before it was defined.
public/res/extensions/htmlSanitizer.js: line 348, col 14, 'htmlSanitizeWriter' was used before it was defined.

5 errors
public/res/extensions/markdownSectionParser.js: line 106, col 13, 'offset' was used before it was defined.

1 error
[05:13:30] Finished 'copy-font' after 15 s
public/res/extensions/notifications.js: line 80, col 14, 'updateOnlineStatus' was used before it was defined.

1 error
public/res/extensions/scrollSync.js: line 135, col 9, 'doScrollSync' was used before it was defined.

1 error
[05:13:30] Finished 'less' after 16 s
[05:13:30] Finished 'copy-img' after 16 s
public/res/helpers/couchdbHelper.js: line 227, col 14, 'handleError' was used before it was defined.

1 error
public/res/helpers/dropboxHelper.js: line 76, col 22, 'localAuthenticate' was used before it was defined.
public/res/helpers/dropboxHelper.js: line 249, col 14, 'handleError' was used before it was defined.

2 errors
public/res/helpers/githubHelper.js: line 83, col 22, 'getCode' was used before it was defined.
public/res/helpers/githubHelper.js: line 103, col 22, 'getToken' was used before it was defined.
public/res/helpers/githubHelper.js: line 147, col 22, 'write' was used before it was defined.
public/res/helpers/githubHelper.js: line 247, col 14, 'handleError' was used before it was defined.

4 errors
public/res/helpers/googleHelper.js: line 208, col 22, 'oauthRedirect' was used before it was defined.
public/res/helpers/googleHelper.js: line 219, col 22, 'startAuthenticate' was used before it was defined.
public/res/helpers/googleHelper.js: line 619, col 14, 'handleError' was used before it was defined.
public/res/helpers/googleHelper.js: line 829, col 22, 'publish' was used before it was defined.

4 errors
public/res/helpers/sshHelper.js: line 68, col 14, 'handleError' was used before it was defined.

1 error
public/res/helpers/tumblrHelper.js: line 63, col 22, 'oauthRedirect' was used before it was defined.
public/res/helpers/tumblrHelper.js: line 70, col 22, 'getVerifier' was used before it was defined.
public/res/helpers/tumblrHelper.js: line 89, col 22, 'getAccessToken' was used before it was defined.
public/res/helpers/tumblrHelper.js: line 158, col 14, 'handleError' was used before it was defined.

4 errors
public/res/helpers/wordpressHelper.js: line 54, col 22, 'getCode' was used before it was defined.
public/res/helpers/wordpressHelper.js: line 73, col 22, 'getToken' was used before it was defined.
public/res/helpers/wordpressHelper.js: line 158, col 14, 'handleError' was used before it was defined.

3 errors
public/res/providers/couchdbProvider.js: line 320, col 13, '$selectTagElt' was used before it was defined.

1 error
public/res/core.js: line 453, col 18, 'applyTheme' was used before it was defined.

1 error
public/res/editor.js: line 65, col 9, 'fileChanged' was used before it was defined.
public/res/editor.js: line 300, col 17, 'longerDebouncedSave' was used before it was defined.
public/res/editor.js: line 399, col 9, 'selectionMgr' was used before it was defined.
public/res/editor.js: line 412, col 9, 'textContent' was used before it was defined.
public/res/editor.js: line 645, col 9, 'undoMgr' was used before it was defined.
public/res/editor.js: line 675, col 14, 'checkContentChange' was used before it was defined.
public/res/editor.js: line 724, col 14, 'adjustCommentOffsets' was used before it was defined.
public/res/editor.js: line 916, col 13, 'action' was used before it was defined.
public/res/editor.js: line 935, col 13, 'actions' was used before it was defined.
public/res/editor.js: line 1002, col 9, 'sectionList' was used before it was defined.
public/res/editor.js: line 1007, col 14, 'updateSectionList' was used before it was defined.
public/res/editor.js: line 1068, col 14, 'highlightSections' was used before it was defined.
public/res/editor.js: line 1111, col 14, 'addTrailingLfNode' was used before it was defined.
public/res/editor.js: line 1132, col 14, 'highlight' was used before it was defined.

14 errors
public/res/layout.js: line 217, col 14, 'onResize' was used before it was defined.
public/res/layout.js: line 271, col 14, 'resizeAll' was used before it was defined.
public/res/layout.js: line 657, col 13, 'closeTimeoutId' was used before it was defined.

3 errors
[05:13:32] 'jshint' errored after 17 s
[05:13:32] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: public/res/classes/AsyncTask.js, public/res/extensions/comments.js, public/res/extensions/documentManager.js, public/res/extensions/documentPanel.js, public/res/extensions/findReplace.js, public/res/extensions/htmlSanitizer.js, public/res/extensions/markdownSectionParser.js, public/res/extensions/notifications.js, public/res/extensions/scrollSync.js, public/res/helpers/couchdbHelper.js, public/res/helpers/dropboxHelper.js, public/res/helpers/githubHelper.js, public/res/helpers/googleHelper.js, public/res/helpers/sshHelper.js, public/res/helpers/tumblrHelper.js, public/res/helpers/wordpressHelper.js, public/res/providers/couchdbProvider.js, public/res/core.js, public/res/editor.js, public/res/layout.js
[05:13:32] 'default' errored after 17 s
[05:13:32] Error: [object Object]
    at formatError (/Users/benjamin.dean/.nvm/versions/node/v4.1.0/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/benjamin.dean/.nvm/versions/node/v4.1.0/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/benjamin.dean/GIT_CLONES/stackedit/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/benjamin.dean/GIT_CLONES/stackedit/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/benjamin.dean/GIT_CLONES/stackedit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/benjamin.dean/GIT_CLONES/stackedit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/benjamin.dean/GIT_CLONES/stackedit/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/benjamin.dean/GIT_CLONES/stackedit/node_modules/run-sequence/index.js:45:4)
```

**Comment by kainecy** [comment]
same to me

**Comment by davepoltorak** [comment]
I've been trying to build this over the last few days and am having the same problem.

I'm not as familiar with requirejs as I'd like (as well as the other technologies used) but a quick search shows that gulp-requirejs is blacklisted (by gulp) and requirejs should be used directly. I'm not sure if blacklisting would cause a failure but as it fails at the requirejs step....

Has anyone managed to resolve? No new commits recently and I can't see a PR that would address this issue.

**Comment by davepoltorak** [comment]
Removing jshint from the build pipeline resolves the build issue. (I removed the line 217 in Gulpfile.js to remove the jshint from the default build pipeline)

**Comment by liangzai-cool** [comment]
same to me

**Comment by benweet** [comment]
Should be fixed with the v5.
